### ISSUE TITLE
Command: Storywriting

### ISSUE THREAD

**Issue by maartenberg** [RobinSikkens/Sticky-discord#3]
Each time the command `!addstory word word word` is run, the given words should be appended to the running story.

`!story` should concatenate all words entered and print the story until now, or be passed an id to print a finished story, along with it's authors.

`!endstory [title]` should finalize the story and save it under the given title, and clear the story buffer.

**Comment by RobinSikkens** [comment]
Is implemented as of commit 423db3a6bd00cf020b50dfb405a7b7da0ed56f02
